config/routes.rb
Mixx96Deals::Application.routes.draw do
  resources :deals do
		resources :orders do
      get 'failure', :on => :member
      get 'success', :on => :member
    end
	end


  resources :orders
  resources :merchants

  devise_for :users

  get 'deal/:id', :to => 'deals#show', as: 'deal'
  get 'coupon/:id', :to => 'coupons#show', as: 'coupon'
  get 'ad/:id', :to => 'ads#show', as: 'ad'
  get 'event/:id', :to => 'events#show', as: 'event'


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'site#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
	#relationships
	belongs_to :deal
	belongs_to :user
  has_one :offer, :through => :deal
	has_many :transactions, :class_name => "OrderTransaction", :dependent => :destroy
  has_one :merchant, :through => :deal

	#mass-assigment
  attr_accessible :address, :address2, :city, :state, :zip, :card_number, :card_verification, 
  :first_name, :last_name, :card_type, :card_expires_on, :deal_id, :completed, :number #(1i), card_expires_on(2i), card_expires_on(3i)

  #virtual things
  attr_accessor :card_number, :card_verification

  #callbacks
  before_validation :generate_order_number, :on => :create
  
  #validations
  validates_presence_of :address, :city, :state, :zip,  
  :first_name, :last_name, :card_type, :card_expires_on
  validate :validate_card, :on => :create

  #scopes
  scope :completed, lambda { where :completed => true }
  scope :incomplete, lambda { where :completed => false }
  scope :all, lambda { all }
  scope :recent, limit(10)
  
  #methods
  def purchase
    response = ::GATEWAY.purchase(price_in_cents, credit_card, purchase_options)
    transactions.create!(:action => "purchase", :amount => price_in_cents, :response => response)
    response.success?
  end
  
  def price_in_cents
    (deal.price*100).round
  end

  def complete!
    if self.deal.quantity != nil && self.deal.quantity > 0
			self.deal.decrement!(:quantity)
      logger.debug "****************** DEAL QUANTITY DECREASED BY 1 ****************"
    end
  	toggle!(:completed)
  	logger.debug "****************** ORDER MARKED COMPLETED ****************"
  end

  private
  
  def purchase_options
    {
      :ip => ip_address,
      :billing_address => {
        :name     => "#{first_name} #{last_name}",
        :address1 => address,
        :city     => city,
        :state    => state,
        :country  => "US",
        :zip      => zip
      }
    }
  end
  
  def validate_card
    unless credit_card.valid?
      credit_card.errors.each do |k,v|
      	logger.debug "*" * 50
      	logger.debug "#{k} => #{v}"
      	logger.debug "*" * 50
      	case k
      		when  "year" || "month"
      			errors.add(:card_expires_on, v.join)
        	when "number"
        		errors.add(:card_number, v.join)
        	when "brand"
        		errors.add(:card_type, v.join)
        end
      end
    end
  end
  
  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :type               => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => first_name,
      :last_name          => last_name
    )
  end

  def generate_order_number
    record = true
    while record
      random = "M#{Array.new(9){rand(9)}.join}"
      record = self.class.where(:number => random).first
    end
    self.number = random if self.number.blank?
    self.number
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
	before_filter :authenticate_user!

	def index
		@orders = current_user.orders.completed
	end

	def show
		@order = current_user.orders.find(params[:id])
	end

	def create
		@order = current_user.orders.build(params[:order])
		@order.ip_address = request.remote_ip
		@order.deal = Deal.find(params[:deal_id])
		if @order.save
			if @order.purchase
				@order.complete!
        OrderMailer.order_confirmation(current_user, @order).deliver
				redirect_to success_deal_order_path(@order.deal,@order)
			else
				redirect_to failure_deal_order_path(@order.deal,@order)
			end
			# end
		else
			render 'new'
		end
	end

	def edit
		@order = current_user.orders.find(params[:id])
	end

	def update
		@order = current_user.orders.find(params[:id])
		@order.ip_address = request.remote_ip
		if @order.update_attributes(params[:order])
			if @order.purchase
				@order.complete!
				OrderMailer.order_confirmation(current_user, @order).deliver
				redirect_to success_deal_order_path(@order.deal,@order)
			else
				redirect_to failure_deal_order_path(@order.deal,@order)
			end
		else
			render 'new'
		end
	end

	def failure
		@order = current_user.orders.find(params[:id])
	end

	def success
		@order = current_user.orders.find(params[:id])
	end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for [:deal,@order], :input_html => { :class => 'default_class' }  do |f| %>
  <%= f.error_notification %>

    <fieldset>
      <legend>Billing Address</legend>
      <%= f.input :first_name, :required => :true %>
      <%= f.input :last_name, :required => :true %>
      <%= f.input :address, :required => :true %>
      <%= f.input :address2 %>
      <%= f.input :city, :required => :true %>
      <%= f.input :state, :as => :select, :collection => us_states, :required => :true, :selected => "WA" %>
      <%= f.input :zip, :required => :true %>
    </fieldset>
    <fieldset>
      <legend>Payment Info</legend>
      <%= f.input :card_type, :as => :select, :collection => [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]], :required => :true %>
      <%= f.input :card_number, :required => :true %>
      <%= f.input :card_verification, :label => 'Card Verification Value (CVV)', :required => :true %>
      <%= f.input :card_expires_on, :as => :date, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
    </fieldset>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/failure.html.erb
<h1>Order Failed</h1>
<div class="alert alert-block alert-error">
  <h4 class="alert-heading">Oh no!</h4>
  <%= @order.transactions.last.message %>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<h1 class="page-header">Order History</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Deal</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Order Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @orders.each do |order| %>
  <tr>
    <td><%= order.deal.name %></td>
    <td><%= order.address %></td>
    <td><%= order.address2 %></td>
    <td><%= order.city %></td>
    <td><%= order.state %></td>
    <td><%= order.zip %></td>
    <td><%= order.created_at.to_s(:short) %>
    <td><%= link_to 'Show', success_deal_order_path(order.deal,order) %></td>
  </tr>
<% end %>
  </tbody>
</table>

<!-- <td><%#= link_to 'Edit', edit_order_path(order) %></td>
<td><%#= link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete %></td> -->

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', deal_orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Thanks for your order <%= @order.user.email %></h1>
<p>
  <b>Address:</b>
  <%= @order.address %>
</p>

<p>
  <b>Address2:</b>
  <%= @order.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @order.city %>
</p>

<p>
  <b>State:</b>
  <%= @order.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @order.zip %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/success.html.erb
<h1>Order Success!</h1>