config/routes.rb
Mixx96Deals::Application.routes.draw do
  resources :deals do
		resources :orders do
      get 'failure', :on => :member
      get 'success', :on => :member
    end
	end


  resources :orders
  resources :merchants

  devise_for :users

  get 'deal/:id', :to => 'deals#show', as: 'deal'
  get 'coupon/:id', :to => 'coupons#show', as: 'coupon'
  get 'ad/:id', :to => 'ads#show', as: 'ad'
  get 'event/:id', :to => 'events#show', as: 'event'


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'site#index'
end

app/models/deal.rb
class Deal < Offer
  #validations
  validates_presence_of :name, :tagline, :description, :normal_price, :price, :end_date, :expiration_date, :image, :merchant
  validates_uniqueness_of :name
  validates_numericality_of :normal_price, :price, :quantity

  #mass-assigment
  attr_accessible :name, :tagline, :description, :normal_price, :price, :start_date, :end_date, :expiration_date, :quantity, :image, :merchant_id, :category_ids, :image_cache, :featured, :priority
  
  #scopes
  scope :recent, limit(5)
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def show
  	@deal = Deal.find(params[:id])
  end

  def feedback
    
  end
end

app/helpers/deals_helper.rb
module DealsHelper

  def deal_savings(deal)
    number_to_percentage( ((deal.normal_price.to_f - deal.price.to_f) / deal.normal_price.to_f ) * 100, precision: 0)
  end

end

app/views/deals/show.html.erb
<div class="row">
	<div class="span4">
		<%= image_tag @deal.image.url %>
	</div>

	<div class="span4">
		
		<h1><%= @deal.name %></h1>
		<p><%= @deal.tagline %></p>
		<div class="btn-group" id="purchase-buttons">
      <button class="btn">You Save <%= deal_savings(@deal) %></button>
      <% unless @deal.quantity.blank? %>
	  		<button class="btn"><%= pluralize(@deal.quantity, 'deal') %> left.</button>
      <% end %>  
      <button class="btn">Your Cost <%= number_to_currency @deal.price %></button>
	  		<%= link_to 'Buy', new_deal_order_path(@deal), class: 'btn btn-success' %>
		</div>
	</div><!-- span5 -->
</div><!-- row -->

<div class="row">
	
	<div class="span4">
		<h4 class="deal-header4">Things you need to know about this Deal:</h4>
		<%= simple_format @deal.description %>
		<h6>PAID VALUE DOES NOT EXPIRE.<br />PROMOTIONAL VALUE EXPIRES ON <%= @deal.expiration_date.strftime("%b %d, %Y").upcase %>. <%= link_to '*', 'http://mixx96.com/component/content/article/152' %></h6>
		<h6 class="header-conditons">General Conditions:</h6>
		<p class="general-conditions">This certificate cannot be combined with any other offer, promotion or coupon.<br />Tax and gratuity, where applicable, are not included.<br />Where it says  PROMOTIONAL VALUE EXPIRES: (DATE) it means that the extra value on the  certificate expires on the date shown. After that date, the value of the coupon or deal reverts to only the amount you paid. The "PAID VALUE" DOES NOT EXPIRE.  (Example: You bought a box of donuts (cost $12) for $5.  You can take the coupon to the donut shop and get $12 of donuts until the expiration date.  After the  expiration date, you'll only get $5 worth of dounts.)<br />If for some reason the wonderful donut shop closes , we will provide refunds upon request only where the merchant has gone out of business before the promotional period ends.</p>
	</div>

	<div class="span4">

		<div class="thumbnail">
			<%= image_tag @deal.merchant.logo.url(:thumb) unless @deal.merchant.logo.blank? %>
			<h5><%= @deal.merchant.name %></h5>
			<address>
				<%= @deal.merchant.address %> <br>
				<% unless @deal.merchant.address2.blank? %>
					<%= @deal.merchant.address2 %> <br>
				<% end %>
				<%= "#{@deal.merchant.city} #{@deal.merchant.state}, #{@deal.merchant.zip}" %>
			</address>
			<% unless @deal.merchant.phone_number.blank? %>
				<phone><%= @deal.merchant.phone_number %></phone>
			<% end %>
			<email><%= @deal.merchant.email %></email>
			<%# unless @deal.merchant.twitter.blank? %>
				<%#= @deal.merchant.twitter %>
			<%# end %>
			<br />
			<map><%= link_to "Map & Directions", @deal.merchant.map_link, class: 'btn', target: '_blank' %></map>
		</div>
		<div class="span5" id="socialSharing">
		    <span class='st_sharethis_hcount' displayText='ShareThis'></span>
		    <span class='st_facebook_hcount' displayText='Facebook'></span>
		    <span class='st_twitter_hcount' displayText='Tweet'></span>
		    <span class='st_email_hcount' st_image='http://deals.mixx96.com/<%= @deal.image.url %>' st_url='http://deals.mixx96.com/<%= url_for(:only_path => true) %>' displayText='Email'></span>
		</div>
	</div>
</div>