config/routes.rb
Mixx96Deals::Application.routes.draw do
  resources :deals do
		resources :orders do
      get 'failure', :on => :member
      get 'success', :on => :member
    end
	end


  resources :orders
  resources :merchants

  devise_for :users

  get 'deal/:id', :to => 'deals#show', as: 'deal'
  get 'coupon/:id', :to => 'coupons#show', as: 'coupon'
  get 'ad/:id', :to => 'ads#show', as: 'ad'
  get 'event/:id', :to => 'events#show', as: 'event'


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'site#index'
end

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Mixx96Deals</title>
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
  <link href="http://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
  <style type="text/css">
    #mc_embed_signup{background:transparent; clear:left; font:14px Helvetica,Arial,sans-serif; }
  </style>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>  
</head>
<body class="<%= params['action'] %>">
	<div id="page-background">
    <%= image_tag 'bg.png', width: "100%", height: "100%" %>
  </div>
	  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
	  <header>
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">

            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <%= image_tag('mixxlogo-thumb.png', alt: 'Mixx96', class: 'brand-img')%>
            <%= link_to 'Mixx96Deals', root_url, class: 'brand' %>  
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="<%= 'active' if params[:controller] == 'merchants' %>"><%= link_to "Merchants", merchants_path %></li>
              </ul>
              <ul class="nav pull-right">
                <li class="divider-vertical"></li>
                <% if current_user %>
                  <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                  <li class="divider-vertical"></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Login', new_user_session_path %></li>
                  <li class="divider-vertical"></li>
                  <li><%= link_to 'Register', new_user_session_path %></li>
                <% end %>
              </ul>
            </div> <!-- .nav-collapse collapse -->
          </div>
        </div>
      </div>
  	</header>

  <div class="container">
		<% flash.each do |name, msg| %>
  		<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    		<a class="close" data-dismiss="alert">×</a>
    		<%= msg %>
  		</div>
		<% end %>

		<div class="row">
      <div id="main" class="span9 pull-right <%= 'white-bg' if params[:controller] != 'site' %>" role="main">
        <div class="pad-box">
          <%= yield %>
        </div>
      </div><!--#main -->
      
      <div class="span3">
  			 <div id="asides" class="clearfix">
          <h1 class="brand"><a href="http://mixx96.com/"><%= image_tag('mixxlogo.png', alt: 'Mixx96')%></a></h1>
          <div class="well sidebar-nav">
  				<h2><%= link_to 'http://twitter.com/mixx96' do %>
                <%= image_tag "twitter-bird-dark-bgs.png", alt: "Twitter", height: '44px', width: '44px', style: 'vertical-align:middle;' %>
                @Mixx96
               <% end %>
            <br/>(360) 943-9937</h2>
          <ul class="nav nav-list">
            <li><a href="/">All Categories</a></li>
            <% Category.order(:sort).all.each do |category| %>
            <% unless category.offers.empty? %>
              <li><a href="/?category=<%= category.name.parameterize %>" class="<%= "active" if params['category'] == category.name.parameterize %>"><%= category.name %></a></li>
              <% end %>
            <% end %>
          </ul><!-- .nav .nav-list -->

          <div id="mailing-list">
            <!-- Begin MailChimp Signup Form -->
            <div id="mc_embed_signup">
              <form action="http://mixx96.us6.list-manage.com/subscribe/post?u=a0b34a63a5afefb49ab81a5fe&amp;id=f84f41be09" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <label for="mce-EMAIL">Subscribe to our mailing list</label>
                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                <div class="clear">
                  <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn">
                </div>
              </form>
            </div>
            <!--End mc_embed_signup-->
          </div><!-- mailing-list -->
          <!-- <div class="blend">
            <script src="http://einmaleins.co/blend/members.js" type="text/javascript"></script>
          </div> -->
        </div><!-- .well .sidebar-nav -->
			 </div><!--#asides -->
      </div><!-- span3 -->


			
		</div><!--.row-->
	</div><!--.container-->


    <footer>
      <div class="container">
        <hr/>
        <p>&copy; 2013. MIXX 96.1. All Rights Reserved | <a href="http://mixx96.com/component/content/article/152">Privacy Policy</a> | Site Development By <a href="http://einmaleins.co" target="_blank">Einmaleins</a>.</p>
      </div>
    </footer>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "ur-496b58d8-a208-835b-5671-3827d6a9f5f0"});</script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41503726-1', 'mixx96.com');
  ga('send', 'pageview');

</script>
</body>
</html>